---
development:
    hostname: localhost:3000
    listen: 0.0.0.0:3000 
    driver: sqlite3
    data_source: ./sqlite.db
    goroot: /Users/skyblue/go

production:
    hostname: gobuild.io
    listen: 0.0.0.0:3000
    driver: sqlite3
    data_source: ./sqlite.db
    goroot: /usr/local/go 
    # qiniu
    access_key: BgESh3GconLxVmqlkM19U3ANknrCsTWwIx67S3fo
    secret_key: xxxx
